sudo: false
env:
  - CXX=g++-4.8
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
before_install:
  - npm i -g npm@^2.0.0
  - npm install -g bower
  - npm install
  - bower install
before_script:
  - npm prune
script:
  - npm run -s build
  - npm run -s examples
after_success:
  - npm run semantic-release
  - echo $GH_TOKEN | pulp login
  - test -n "$TRAVIS_TAG" && ( yes | pulp publish --no-push )
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
